# Generated by Django 4.0.4 on 2022-05-01 03:35

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_type', models.CharField(choices=[('SOL', 'Solid'), ('GRD', 'Gradient'), ('PXB', 'Pixabay'), ('GIF', 'GIF')], max_length=3, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.device', verbose_name='User Mobile Device ID')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
