# Generated by Django 4.0.4 on 2022-05-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.device', verbose_name='User Mobile Device ID'),
        ),
    ]
