# Generated by Django 4.0.4 on 2022-05-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='device_id',
            new_name='device',
        ),
    ]
