# Generated by Django 4.0.4 on 2022-05-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_rename_device_id_collection_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_type',
            field=models.CharField(choices=[('SOL', 'Solid'), ('GRD', 'Gradient'), ('PXB', 'Pixabay')], max_length=3, null=True),
        ),
    ]
